all: bst_array bst_link bst-traversal-link bst-traversal-array

bst_array:

bst_link:

bst-traversal-link:

bst-traversal-array:

clean:
	rm -f ./bst_array
	rm -f ./bst_link
	rm -f ./bst-traversal-link
	rm -f ./bst-traversal-array
